# https://taskfile.dev

version: '3'

includes:
  docker:
    taskfile: ./docker/Taskfile.yml
    dir: .

dotenv: ['.env']

tasks:
  lint:
    desc: run the linter
    cmds:
      - |
        goimports -w ./internal/*
        golangci-lint run ./...
  install-lefthook:
    desc: install lefthook in git actions
    cmd: lefthook install

  build-server:
    desc: build the server
    cmds:
      - |
        go build .

  build-client:
    desc: build the client
    dir: client
    cmds:
      - |
        echo "Building client"
        npm install
        ng build 

  build:
    desc: build the server and client
    cmds:
      - task build-server
      - task build-client
