# https://taskfile.dev

version: '3'

vars:
  DCR: "${DCR}"
  VERSION: 1.0

tasks:

  echo:
    desc: debug
    cmds:
      - |
        echo {{.DCR}}
        echo {{.VERSION}}
  run-server-it:
    desc: "run the server container on video10 and video11. 
        Add environment vars and volume mappings to have a custom client ui
        -e ROOTDIR=/static 
        -v $(pwd)/data:/static "
    cmds:
      - |
        docker run -it --rm \
        --device /dev/video10 \
        --device /dev/video11 \
        --network host \
        --entrypoint /bin/bash \
        -e GST_DEBUG=3 \
        -e PIPELINE="v4l2src device=/dev/video10 ! queue ! videoconvert ! vp8enc target-bitrate=3000000 keyframe-max-dist=240 deadline=1 ! queue ! fakesink" \
        --name live-stream \
        {{.DCR}}pion-webrtc-server:{{.VERSION}}
  run-server:
    desc: "run the server container on video10 and video11. 
        Add environment vars and volume mappings to have a custom client ui
        -e ROOTDIR=/static 
        -v $(pwd)/data:/static "

    cmds:
      - |
        docker run -it --rm \
        --device /dev/video10 \
        --device /dev/video11 \
        --network host \
        -e GST_DEBUG=3 \
        -e PIPELINE="v4l2src device=/dev/video10 ! queue ! videoconvert ! vp8enc target-bitrate=3000000 keyframe-max-dist=240 deadline=1 ! queue ! appsink emit-signals=true name=sink" \
        --name live-stream \
        {{.DCR}}pion-webrtc-server:{{.VERSION}}
  build-server:
    desc: build the docker container set with ARCH="linux/amd64""
    cmds:
      - |
        docker build \
        --platform linux/amd64 \
        --build-arg PLATFORM=amd64 \
        -t {{.DCR}}pion-webrtc-server:{{.VERSION}} \
        -f docker/server.dockerfile \
        .
  build-server-arm:
    desc: build the docker container set with ARCH="linux/arm64""
    cmds:
      - |
        docker build \
        --platform linux/arm64 \
        --build-arg PLATFORM=arm64v8 \
        -t {{.DCR}}pion-webrtc-server:{{.VERSION}} \
        -f docker/server.dockerfile \
        .
  run-client:
    desc: run the client
    cmds:
      - |
        docker run -d --rm \
        --network host \
        --name live-stream-client \
        -e WEBRTC_SERVER_LOCATION=ws://localhost:8080/ws \
        {{.DCR}}pion-webrtc-client:{{.VERSION}}
  build-client:
    desc: build the docker container set with ARCH="linux/amd64"
    cmds:
      - |
        docker build \
        --platform linux/amd64 \
        --build-arg PLATFORM=amd64 \
        -t {{.DCR}}pion-webrtc-client:{{.VERSION}} \
        -f docker/client.dockerfile \
        .
  build-client-arm:
    desc: build the docker container set with ARCH="linux/arm64"
    cmds:
      - |
        docker build \
        --platform linux/arm64 \
        --build-arg PLATFORM=arm64v8 \
        -t {{.DCR}}pion-webrtc-client:{{.VERSION}} \
        -f docker/client.dockerfile \
        .
